-- Supabase/Postgres hardening: block direct anon/client table access by default.
-- No public policies are created here; the backend remains the authorization gate.

ALTER TABLE "app_users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_avatars" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "session_manager" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "begs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "donations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "admin_actions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "operational_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "admin_invites" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "reports" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "gratitude_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_stats" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_trust" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "cooldowns" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_verifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "donor_ranks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "saved_cards" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "bank_accounts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "withdrawals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "stories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "reactions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "support_tickets" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "support_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "support_chats" ENABLE ROW LEVEL SECURITY;
